all:
  vars:
    ansible_user: ubuntu
  children:
    k8s_control_plane:
      hosts:
        k8s-control-plane.local:
    
    k8s_workers:
      hosts:
        k8s-worker-0.local:
        k8s-worker-1.local:
        k8s-worker-2.local:
